import React from "react";

function Body() {
  return (
    <React.Fragment>
      {" "}
      I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM
      BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY
      I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM
      BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY
      I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM
      BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY
      I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM
      BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY
      I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM
      BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY
      I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM BODY I AM
      BODY I AM BODY I AM BODY I AM BODY{" "}
    </React.Fragment>
  );
}

export default Body;
